// Top-level gradle script.

buildscript {
    repositories {

        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
        maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
     }

}

allprojects {
    repositories {
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        mavenCentral()
    }
}

