apply plugin: 'com.android.library'

android {
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }
    namespace 'com.lefebure.ntripclient'
    lint {
        targetSdk 28
    }
    testOptions {
        targetSdk 28
    }
}
